export const SIGNUP_REQUEST: string = 'SIGNUP_REQUEST';
export const SIGNUP_RECEIVED: string = 'SIGNUP_RECEIVED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED';

export const PRESENCE_REQUEST = 'PRESENCE_REQUEST';
export const PRESENCE_RECEIVED = 'PRECENCE_RECEIVED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED';
